services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper
    ports:
      - "9000:9000"
    volumes:
      - whisper-models:/root/.cache/whisper
    environment:
      - ASR_MODEL=base  # tiny, base, small, medium, large
      - ASR_ENGINE=faster_whisper
    networks:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  proxy:
    external: true

volumes:
  whisper-models:
